QPPA-4750: Updated node packages, gitignore file
CMSgov/qpp-submissions-docs pull request #193
Opened 2021-01-06 20:17 UTC by ckawell

Updated react-scripts, eslint, babel, and jest node packages to latest versions as a security upgrade.
Also added .eslintcache to gitignore until the file is removed in a later react-scripts version.

2021-01-06 20:19 UTC, ckawell commented
NOTE: the /image folder references were also removed since the folder does not exist and was causing compile errors with newer node packages. The change to tsconfig is added automatically by react-scripts@4.0.1 which fixes an issue caused in v4.0.0

2021-01-07 14:24 UTC, nickelstar requested changes
The .snyk file needs to be updated to remove the 'ignore' for the react-scripts. Thanks.

2021-01-07 16:40 UTC, ckawell commented
> The .snyk file needs to be updated to remove the 'ignore' for the react-scripts. Thanks.

Done, thanks for the reminder

2021-01-08 15:25 UTC, nickelstar approved these changes

2021-01-11 17:15 UTC, bartcone approved these changes

2021-01-11 17:15 UTC, merged