QPPA-6710 & QPPA-6757: Updates Announcements & Creates Error Codes link
CMSgov/qpp-submissions-docs pull request #252
Opened 2022-08-22 19:45 UTC by john-manack

## Description
- Y6 changes to annoucements
- Adds `Error Codes` to left nav with link to devpre error codes page.

## How Has This Been Tested?

- verified locally
- ran test suite

## Screenshots:
<img width="1431" alt="Screen Shot 2022-08-22 at 3 42 19 PM" src="https://user-images.githubusercontent.com/74992804/186005595-0c4898d0-bda2-495e-accf-72d9d2d72208.png">
<img width="1380" alt="Screen Shot 2022-08-22 at 3 43 40 PM" src="https://user-images.githubusercontent.com/74992804/186005601-41027f47-bc30-46bf-afcc-12aa48cd61e1.png">

## Types of Changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have updated the Last-Updated value on all documentation pages where I changed content.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] Updated documentation (`README.md`, etc.) depending if the changes require it.

2022-08-23 17:59 UTC, ckawell-sb approved these changes

2022-08-23 18:10 UTC, davidberry-sb approved these changes

2022-08-25 12:38 UTC, peg-uehling requested changes
Instead of showing the URL as a bullet - just make the "Developer Preview Documentation" in the statement the hyperlink out.

2022-08-25 13:35 UTC, john-manack commented
> Instead of showing the URL as a bullet - just make the "Developer Preview Documentation" in the statement the hyperlink out.

@peg-uehling good callout - I've updated the code and screenshot above.

2022-08-25 15:10 UTC, peg-uehling approved these changes

2022-08-25 15:12 UTC, merged